# Autogenerated wrapper script for libde265_jll for aarch64-apple-darwin
export libde265

JLLWrappers.@generate_wrapper_header("libde265")
JLLWrappers.@declare_library_product(libde265, "@rpath/libde265.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libde265,
        "lib/libde265.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
