# Autogenerated wrapper script for libde265_jll for x86_64-w64-mingw32-cxx11
export libde265

JLLWrappers.@generate_wrapper_header("libde265")
JLLWrappers.@declare_library_product(libde265, "libde265.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libde265,
        "bin\\libde265.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
